name: Build and Publish to DockerHub

on:
  workflow_dispatch:
    inputs:
      xray_version:
        required: true
        description: version number, eg. 1.2.3
      set_latest:
        type: boolean
        description: set this version as latest tag

env:
  XRAY_VERSION: ${{ github.event.inputs.xray_version || github.ref_name }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Building xray version $XRAY_VERSION"

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          build-args: |
            XRAY_VERSION=${{ env.XRAY_VERSION }}
          tags: ${{ format(github.event.inputs.set_latest && '{0}/xray-gateway:{1},{0}/xray-gateway:latest' || '{0}/xray-gateway:{1}', secrets.DOCKERHUB_USERNAME, env.XRAY_VERSION) }}
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
